[build]
  NODE_ENV = "production"
  command = "npm run build"
  publish = "dist"
[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
[context.branch-deploy.environment]
  NODE_ENV = "production"
