on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://httpster.io"
        expected-statuses: "200,301"
